apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mastodon-twitter-poster-cert
spec:
  commonName: crossposter.f0x.es
  dnsNames:
  - crossposter.f0x.es
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  secretName: mastodon-twitter-poster-cert
