apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mastodon-cert
spec:
  commonName: f0x.es
  dnsNames:
  - f0x.es
  - www.f0x.es
  - streaming.f0x.es
  - mastodon.f0x.es
  - assets.f0x.es
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  secretName: mastodon-cert
