apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres-default-network-policy
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {}
  - from:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 5432
